stages:
  - lint
  - test
  - build
  - security

variables:
  REGISTRY_URL: "oci.vvtechsolutions.eu"
  IMAGE_NAME: "kube-lens"

lint_python:
  stage: lint
  image: python:3.12-slim
  script:
    - pip install -e .[dev]
    - ruff check src/
    - ruff format --check src/
    - mypy src/
    - deptry .

test_python:
  stage: test
  image: python:3.12-slim
  script:
    - pip install -e .[dev]
    - pytest --cov=src --cov-report=xml --cov-report=term
  artifacts:
    reports:
      coverage_report:
        coverage_format: cobertura
        path: coverage.xml
  only:
    - main

build_image:
  stage: build
  image: quay.io/buildah/stable:latest
  variables:
    BUILDAH_ISOLATION: chroot
    STORAGE_DRIVER: overlay
  before_script:
    - echo "$REGISTRY_PASSWORD" | buildah login -u "$REGISTRY_USER" --password-stdin "$REGISTRY_URL"
  script:
    - |
      buildah build \
        --platform linux/arm64 \
        --tag "$REGISTRY_URL/$IMAGE_NAME:$CI_COMMIT_SHORT_SHA" \
        --tag "$REGISTRY_URL/$IMAGE_NAME:latest" \
        --layers \
        --cache-to "$REGISTRY_URL/cache" \
        --cache-from "$REGISTRY_URL/cache" \
        .
    - buildah push "$REGISTRY_URL/$IMAGE_NAME:$CI_COMMIT_SHORT_SHA"
    - buildah push "$REGISTRY_URL/$IMAGE_NAME:latest"
    # Source: https://github.com/containers/buildah/blob/main/docs/buildah-build.1.md
  only:
    - main

scan_image:
  stage: security
  image:
    name: aquasec/trivy:latest
    entrypoint: [""]
  variables:    
    GIT_STRATEGY: none
    TRIVY_NO_PROGRESS: "true"
    TRIVY_CACHE_DIR: ".trivycache/"
    FULL_IMAGE_NAME: $REGISTRY_URL/$IMAGE_NAME:$CI_COMMIT_SHORT_SHA
  script:
    - trivy --version
    - time trivy image --download-db-only

    - echo "$REGISTRY_PASSWORD" | trivy registry login --username "$REGISTRY_USER" --password-stdin "$REGISTRY_URL"
    - time trivy image --exit-code 0 --format template --template "@/contrib/gitlab.tpl" --output "$CI_PROJECT_DIR/gl-container-scanning-report.json" "$FULL_IMAGE_NAME"
    - time trivy image --exit-code 0 "$FULL_IMAGE_NAME"
    - time trivy image --exit-code 1 --severity CRITICAL "$FULL_IMAGE_NAME"
  cache:
    paths:
      - .trivycache/
  artifacts:
    paths:
      - gl-container-scanning-report.json
    when: always
  allow_failure: false
