stages:
  - build
  - test
  - security

variables:
  REGISTRY_URL: "oci.vvtechsolutions.eu"
  IMAGE_NAME: "kube-lens"

build_image:
  stage: build
  image: quay.io/buildah/stable:latest
  variables:
    BUILDAH_ISOLATION: chroot
    STORAGE_DRIVER: overlay
  before_script:
    - echo "$REGISTRY_PASSWORD" | buildah login -u "$REGISTRY_USER" --password-stdin "$REGISTRY_URL"
  script:
    - |
      buildah build \
        --platform linux/arm64 \
        --tag "$REGISTRY_URL/$IMAGE_NAME:$CI_COMMIT_SHORT_SHA" \
        --tag "$REGISTRY_URL/$IMAGE_NAME:latest" \
        --layers \
        --cache-to "$REGISTRY_URL/cache" \
        --cache-from "$REGISTRY_URL/cache" \
        .
    - buildah push "$REGISTRY_URL/$IMAGE_NAME:$CI_COMMIT_SHORT_SHA"
    - buildah push "$REGISTRY_URL/$IMAGE_NAME:latest"
    # Source: https://github.com/containers/buildah/blob/main/docs/buildah-build.1.md
  only:
    - main

scan_image:
  stage: security
  image:
    name: aquasec/trivy:latest
    entrypoint: [""]
  script:
    - trivy image --severity HIGH,CRITICAL --exit-code 1 "$REGISTRY_URL/$IMAGE_NAME:$CI_COMMIT_SHORT_SHA"